// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFxWyL6sNPsVGQG8EVVCIgySkJ5EKRLA',
    appId: '1:200652648221:web:5c3ae06babce498d72fbf4',
    messagingSenderId: '200652648221',
    projectId: 'w7lab-e8cc9',
    authDomain: 'w7lab-e8cc9.firebaseapp.com',
    storageBucket: 'w7lab-e8cc9.appspot.com',
    measurementId: 'G-Z1QNKMEDG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpr7zHwNE0BJwfG8Eo_9SodK1nq-hvyg',
    appId: '1:200652648221:android:40f0ad1b7e9eb58a72fbf4',
    messagingSenderId: '200652648221',
    projectId: 'w7lab-e8cc9',
    storageBucket: 'w7lab-e8cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55-Zbz4ofAz6NwJXChd7-2b03Dw54rC8',
    appId: '1:200652648221:ios:61947d7219c308e572fbf4',
    messagingSenderId: '200652648221',
    projectId: 'w7lab-e8cc9',
    storageBucket: 'w7lab-e8cc9.appspot.com',
    iosBundleId: 'com.example.w7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55-Zbz4ofAz6NwJXChd7-2b03Dw54rC8',
    appId: '1:200652648221:ios:6007848d2ee05ac772fbf4',
    messagingSenderId: '200652648221',
    projectId: 'w7lab-e8cc9',
    storageBucket: 'w7lab-e8cc9.appspot.com',
    iosBundleId: 'com.example.w7.RunnerTests',
  );
}
